[package]
name = "wordle"
version = "0.1.0"
edition = "2021"
 
[workspace]
members = ["naive_bot"]
 
[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde = { version = "1", features = ["derive"] }
lazy_static = "1.4"
rand = "0.8.5"
serde_json = "1.0"